version: '3.6'

services:
  
  shop-api:
    build: 
      context: ./shop-api
    container_name: shop-api
    ports:
      - 8080:8080
    depends_on:
      - kafka

  shop-validator:
    build: 
      context: ./shop-validator
    container_name: shop-validator
    ports:
      - 8081:8081
    depends_on:
      - kafka
  
  shop-report:
    build: 
      context: ./shop-report
    container_name: shop-report
    ports:
      - 8082:8082
    depends_on:
      - kafka
  
  shop-retry:
    build: 
      context: ./shop-retry
    container_name: shop-retry
    ports:
      - 8083:8083
    depends_on:
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  kafka:
    image: confluentinc/cp-kafka:6.0.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:9092,OUTSIDE://:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://host.docker.internal:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
    extra_hosts:
      - "host.docker.internal:172.17.0.1"